<!DOCTYPE html>
<html>
    <head>
        <title>
        <meta charset="utf-8" />
    </title>
    </head>
    <body>
    	<h1> Page web ^^ </h1>

    	
       <p>Aujourd'hui nous somme le <? echo date('d/m/Y h:i:s'); ?></p>
    	   
    	   <ul>
    	      <li style="color: blue;">Texte en bleu</li>
    	      <li style="color: red;"> Texte en rouge</li>
    	      <li style="color: green;">Texte en vert</li>
    	      </ul>
              

    </body>
    </html>